# Config file for [Air](https://github.com/air-verse/air) in TOML format

[build]
pre_cmd = ["task tailwind"]
cmd = "task build"
bin = "/tmp/bin/web -dev"
delay = 100
include_ext = ["go", "tpl", "tmpl", "html", "css", "scss", "js", "ts", "sql", "jpeg", "jpg", "gif", "png", "bmp", "svg", "webp", "ico"]
exclude_dir = []

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
