# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:

  default:
    desc: Print available tasks
    cmds:
      - task --list
  
  tidy:
    desc: Tidy modfiles and format .go files
    cmds:
      - go mod tidy -v
      - go fmt ./...

  test:
    desc: Run all tests
    cmds:
      - go test -v -race -buildvcs ./...

  test:cover:
    desc: Run all tests and display coverage
    cmds:
      - go test -v -race -buildvcs -coverprofile=/tmp/coverage.out ./...
      - go tool cover -html=/tmp/coverage.out
  
  audit:
    desc: Run quality control checks
    deps: [test]
    cmds:
      - go mod tidy -diff
      - go mod verify
      - cmd: test -z "$(gofmt -l .)"
        silent: true
      - go vet ./...
      - go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...
      - go run golang.org/x/vuln/cmd/govulncheck@latest ./...

  build:
    desc: Build the cmd/web application
    cmds:
      - go build -o=/tmp/bin/web ./cmd/web
  
  run:
    desc: Run the go app
    deps: [build]
    cmds:
      - /tmp/bin/web -dev
  
  run:live:
    desc: Run the application with reloading on file changes
    cmds:
      - >-
        go run github.com/cosmtrek/air@v1.43.0
        --build.cmd "task build" --build.bin "/tmp/bin/web -dev" --build.delay "100"
        --build.exclude_dir ""
        --build.include_ext "go, tpl, tmpl, html, css, scss, js, ts, sql, jpeg, jpg, gif, png, bmp, svg, webp, ico"
        --misc.clean_on_exit "true"


