# https://taskfile.dev

version: '3'

vars:
  MIGRATIONS_DIR: internal/db/migrations

tasks:

  default:
    desc: Print available tasks
    cmds:
      - task --list

  tailwind:
    desc: run tailwind cli
    cmds:
      - npx @tailwindcss/cli --input ./assets/tailwind.css --output ./assets/static/css/main.css
  
  tailwind:watch:
    desc: run tailwind cli in watch mode
    cmds:
       - npx @tailwindcss/cli --input ./assets/tailwind.css --output ./assets/static/css/main.css --watch

  tidy:
    desc: Tidy modfiles and format .go files
    cmds:
      - go mod tidy -v
      - go fmt ./...

  test:
    desc: Run all tests
    cmds:
      - go test -v -race -buildvcs ./...

  test:cover:
    desc: Run all tests and display coverage
    cmds:
      - go test -v -race -buildvcs -coverprofile=/tmp/coverage.out ./...
      - go tool cover -html=/tmp/coverage.out
  
  audit:
    desc: Run quality control checks
    deps: [test]
    cmds:
      - go mod tidy -diff
      - go mod verify
      - cmd: test -z "$(gofmt -l .)"
        silent: true
      - go vet ./...
      - go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...
      - go run golang.org/x/vuln/cmd/govulncheck@latest ./...

  build:
    desc: Build the cmd/web application
    cmds:
      - go build -o=/tmp/bin/web ./cmd/web
  
  run:
    desc: Run the go app
    deps: [build]
    cmds:
      - /tmp/bin/web -dev
  
  run:live:
    desc: Run the application with reloading on file changes
    cmds:
      - air

  migrate:new:
    desc: Create a new migration file
    deps: [migrate:install]
    cmds:
      - migrate create -ext sql -dir {{.MIGRATIONS_DIR}} -seq {{.CLI_ARGS}}

  migrate:install:
    desc: Install the migrate CLI
    cmds:
      - go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

  sqlc:install:
    desc: Install the sqlc CLI
    cmds:
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

  sqlc:generate:
    desc: Generate sqlc code
    deps: [sqlc:install]
    cmds:
      - sqlc generate

