// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package data

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type User struct {
	ID           int64
	CreatedAt    string
	Name         string
	Email        string
	PasswordHash []byte
	Activated    bool
}
