---
name: 'push to dokku'

on:
  workflow_run:
    workflows: ["tag with date-time"]  # Name of the workflow to wait for
    types:
      - completed
    branches:
      - replace-with-main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@${{ secrets.DOKKU_VPS_ADDR }}:22/${{ vars.DOKKU_APP_NAME }}'
          branch: main
          ssh_private_key: ${{ secrets.DOKKU_VPS_PRIVATE_KEY }}